version: "3"
services:
  angular-app:
    build: .
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    volumes:
      - .:/app
      - /app/node_modules
    command: npx ng serve --host 0.0.0.0
