name: Angular CI/CD

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch:

jobs:
  test:
    name: Exécuter les tests et générer la couverture
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installer les dépendances
        run: npm ci

      - name: Exécuter les tests unitaires
        run: npm run test -- --watch=false --code-coverage
        env:
          CI: true

      - name: Télécharger la couverture vers Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/**/lcov.info
          flags: unittests
          name: rapport-couverture-codecov

  build:
    name: Construire le projet
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installer les dépendances
        run: npm ci

      - name: Construire le projet
        run: npm run build -- --output-path=dist --base-href=/registration-form-app/

      - name: Télécharger les artefacts de build
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    name: Déployer sur GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v3

      - name: Configurer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Installer les dépendances
        run: npm ci

      - name: Télécharger les artefacts de build
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Déployer sur GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
